# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: hsshih <marvin@42.fr>                      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/07/25 16:29:11 by hsshih            #+#    #+#              #
#    Updated: 2019/07/25 20:34:26 by hsshih           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all:
	@gcc -Wall -Werror -Wextra -o ft_tail main.c ft_atoi.c ft_putchar.c \
			ft_create_elem.c ft_putstr.c ft_one.c ft_two.c ft_three.c

clean:
	@rm -f ft_tail

fclean: clean
